name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run-script build
  
    - name: Deploy
      type: git
      repo: https://claire-chow:Yiwen2019@Zhou@github.com/claire-chow/claire-chow.github.io.git  
      branch: main
      message:  now('YYYY-MM-DD HH:mm:ss')
